import { Mermaid, MDXLink } from "@/components/mdx/custom";
import {
  createHeading,
  Paragraph,
  UnorderedList,
  OrderedList,
  ListItem,
  Blockquote,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableHeader,
  TableCell,
  Anchor,
  HorizontalRule,
  Strong,
  Emphasis,
  Pre,
  Code,
  Div,
} from "@/components/mdx/mdx-components";

// Portfolio 특화 컴포넌트 맵
export const portfolioCustomComponents = {
  Link: MDXLink,
  Mermaid,
  h1: createHeading("h1"),
  h2: createHeading("h2"),
  h3: createHeading("h3"),
  h4: createHeading("h4"),
  h5: createHeading("h5"),
  h6: createHeading("h6"),
  p: Paragraph,
  ul: UnorderedList,
  ol: OrderedList,
  li: ListItem,
  blockquote: Blockquote,
  table: Table,
  thead: TableHead,
  tbody: TableBody,
  tr: TableRow,
  th: TableHeader,
  td: TableCell,
  a: Anchor,
  hr: HorizontalRule,
  strong: Strong,
  em: Emphasis,
  pre: Pre,
  div: Div,
  code: Code,
};
